[build]
  command = "yarn build"
  functions = "functions"
  publish = "static"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/graphql"

[[headers]]
  for = "/*"
  [headers.value]
    Access-Control-Allow-Origin = "*"